!ifdef OS_DEFINES !eof
OS_DEFINES = 1

OS_COLOR_BLACK          =   $00
OS_COLOR_LIGHT_BLUE     =   $0D
OS_COLOR_RED            =   $18
OS_COLOR_GREEN          =   $05


OS_CIA_INTERRUPT_CONTROL_REG    = $DC0D
OS_CIA_INTERRUPT_VECTOR         = $0314      ; 1/60 sec
OS_RASTER_INTERRUPT_CONTROL_REG = $D01A
OS_RASTER_LINE_INTERRUPT_REG    = $D012

OS_SCREEN_CONTROL_REG           = $D011
OS_INTERRUPT_STATUS_REGISTER    = $D019

OS_KERNAL_INTERRUPT_HANDLER     = $EA31
OS_ADDR_CUR_BORDER_COLOR        = $D020
